[package]
name = "c2n-visualizer"
version = "0.1.0"
edition = "2021"

[dependencies]
c2n = { path = "..", version = "0.1.0" }
futures = { workspace = true }
anyhow = { workspace = true }
tracing-subscriber = { workspace = true }
rand = { workspace = true }
